FROM ddsderek/alpine:3.16.0

RUN apk update && \
 apk add openjdk8-jre tzdata && \
 cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
 echo Asia/Shanghai > /etc/timezone && \
 apk del tzdata && \
 rm -rf /tmp/* /var/cache/apk/* && \
 mkdir /app

WORKDIR /app