#!/usr/bin/with-contenv bash

if [ ! -f "/etc/nginx/nginx.conf" ]; then
    echo -e "\033[36mnginx.conf 文件不存在,正在创建... \033[0m"
    cp /etc/nginx_bak/nginx.conf /conf/nginx.conf
    ln -s /conf/nginx.conf /etc/nginx/nginx.conf
    if [ -f "/etc/nginx/nginx.conf" ]; then
        echo "nginx.conf 文件创建成功"
    else
        echo "nginx.conf 文件创建失败"
        exit 1
    fi
else
    echo "nginx.conf 文件存在"
fi

if [ ! -d "/etc/nginx/http.d" ]; then
    mkdir -p /etc/nginx/http.d
fi
if [ ! -d "/conf/http.d" ]; then
    mkdir -p /conf/http.d
fi

if [ ! -f "/etc/nginx/http.d/default.conf" ]; then
    echo -e "\033[36mdefault.conf 文件不存在,正在创建... \033[0m"
    cp /etc/nginx_bak/http.d/default.conf /conf/http.d/default.conf
    ln -s /conf/http.d/default.conf /etc/nginx/http.d/default.conf
    if [ -f "/etc/nginx/http.d/default.conf" ]; then
        echo "default.conf 文件创建成功"
    else
        echo "default.conf 文件创建失败"
        exit 1
    fi
else
    echo "default.conf 文件存在"
fi

chown -R nginx:nginx /web