name: Alpine3.17.0-nginx1.22-php81-tiny

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v4
        with:
          context: Alpine3.17.0-nginx1.22-php81-tiny
          file: Alpine3.17.0-nginx1.22-php81-tiny/Dockerfile
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
            linux/ppc64le
            linux/s390x
          push: true
          tags: |
            ddsderek/foundations:Alpine3.17.0-nginx1.22-php81-tiny
