name: Ubuntu20.04-nginx1.16.1-php7.4.20

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v2
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Buildx
        uses: docker/build-push-action@v5
        with:
          context: Ubuntu20.04-nginx1.16.1-php7.4.20
          file: Ubuntu20.04-nginx1.16.1-php7.4.20/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
            ddsderek/foundations:Ubuntu20.04-nginx1.16.1-php7.4.20
